// src/components/home/CodingStats.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import {
  fallbackCodingStats,
  type CodingData,
} from "@/lib/data";
import { config } from "@/lib/config";
import Reveal from "@/components/Reveal.vue";

const { coding } = config;

const TIMEOUT_MS = 4000;

function formatHours(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  return `${h}h ${m}m`;
}

const data = ref<CodingData | null>(null);
const error = ref(false);

let ctrl: AbortController | null = null;
let timer: ReturnType<typeof setTimeout> | null = null;

function renderError() {
  error.value = true;
  data.value = fallbackCodingStats;
}

onMounted(() => {
  if (typeof fetch !== "function") {
    data.value = fallbackCodingStats;
    return;
  }

  ctrl = typeof AbortController === "function" ? new AbortController() : null;
  timer = setTimeout(() => ctrl?.abort(), TIMEOUT_MS);

  fetch("/api/coding-stats", {
    headers: { Accept: "application/json" },
    signal: ctrl ? ctrl.signal : undefined,
  })
    .then((res) => {
      if (!res.ok) throw new Error("HTTP " + res.status);
      return res.json();
    })
    .then((d: { data: CodingData }) => {
      if (timer) clearTimeout(timer);
      const payload = d?.data;
      if (!payload || !Array.isArray(payload.languages)) {
        renderError();
        return;
      }
      data.value = {
        languages: payload.languages,
        total_seconds: payload.total_seconds,
        days_tracked: payload.days_including_holidays ?? payload.days_tracked,
        daily_average: payload.daily_average,
      } as CodingData;
    })
    .catch(() => {
      if (timer) clearTimeout(timer);
      renderError();
    });
});

onUnmounted(() => {
  if (timer) clearTimeout(timer);
  ctrl?.abort();
});

const maxPercent = computed(() =>
  data.value?.languages.length ? data.value.languages[0].percent : 100,
);
</script>

<template>
  <section
    id="codingstat"
    class="px-6 md:px-10 py-24 md:py-36 border-t hairline"
  >
    <div class="max-w-7xl mx-auto">
      <Reveal class="mb-12 md:mb-16">
        <h2
          class="text-3xl md:text-4xl lg:text-5xl font-medium tracking-[-0.03em] leading-[1.05] mb-4 max-w-2xl text-balance"
        >
          {{ coding.heading.pre
          }}<span class="text-accent italic font-medium">{{
            coding.heading.accent
          }}</span
          >{{ coding.heading.post }}
        </h2>
        <p class="text-ink-300 leading-[1.6] max-w-xl">{{ coding.subline }}</p>
      </Reveal>

      <Reveal :delay="1">
        <div class="bezel">
          <div class="bezel-inner p-5 pb-5 md:p-7 md:pb-7 relative">
            <div
              class="cloud cloud-1 -top-24 -right-16 w-[420px] h-[420px]"
              aria-hidden="true"
            ></div>
            <div class="cs-header">
              <p
                class="text-[10px] uppercase tracking-[0.18em] text-ink-400 font-mono mb-0 truncate"
              >
                {{ coding.breakdown }}
              </p>
              <p class="cs-total">
                <span class="cs-total-value">{{
                  data ? formatHours(data.total_seconds) : "—"
                }}</span>
                tracked ·
                <span>{{ data ? data.days_tracked : "—" }}</span> days
              </p>
            </div>
            <p class="cs-total cs-daily">
              avg
              <span class="cs-total-value">{{
                data ? formatHours(data.daily_average) : "—"
              }}</span>
              <span class="cs-daily-label">/ day</span>
            </p>

            <template v-if="data">
              <div
                v-for="(lang, i) in data.languages.slice(0, 6)"
                :key="lang.name"
                class="cs-row"
              >
                <span class="cs-rank">#{{ i + 1 }}</span>
                <div class="cs-lang">
                  <span class="cs-lang-name">{{ lang.name }}</span>
                  <div class="cs-bar">
                    <div
                      class="cs-fill"
                      :style="{ width: `${(lang.percent / maxPercent) * 100}%` }"
                    />
                  </div>
                </div>
                <span class="cs-time">{{ formatHours(lang.total_seconds) }}</span>
                <span class="cs-percent">{{ lang.percent.toFixed(1) }}%</span>
              </div>
            </template>
            <template v-else>
              <div v-for="w in [70, 50, 35, 25, 18, 12]" :key="w" class="cs-row">
                <span class="cs-rank cs-skel">&nbsp;</span>
                <div class="cs-lang">
                  <span class="cs-lang-name cs-skel"
                    >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span
                  >
                  <div class="cs-bar">
                    <div class="cs-fill cs-skel" :style="{ width: `${w}%` }" />
                  </div>
                </div>
                <span class="cs-time cs-skel">&nbsp;&nbsp;&nbsp;</span>
                <span class="cs-percent cs-skel">&nbsp;&nbsp;&nbsp;</span>
              </div>
            </template>

            <p v-if="error" class="mt-4 text-xs font-mono text-ink-400">
              {{ coding.error }}
            </p>
          </div>
        </div>
      </Reveal>
    </div>
  </section>
</template>

// components/CodingStats.tsx
"use client";

import { useEffect, useState } from "react";
import { fallbackCodingStats } from "@/lib/data";
import { config } from "@/lib/config";
import Reveal from "./Reveal";

const { coding } = config;

type CodingStat = { name: string; total_seconds: number; percent: number };
type CodingData = {
  languages: CodingStat[];
  total_seconds: number;
  days_tracked: number;
  days_including_holidays?: number;
  daily_average: number;
};

const WAKAPI_ENDPOINT: string =
  "https://wakapi.sakuspace.my.id/api/compat/wakatime/v1/users/sahaduka/stats/";
const WAKAPI_USERNAME: string = "sahaduka";
const TIMEOUT_MS = 4000;

function formatHours(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  return `${h}h ${m}m`;
}

function CodingRow({
  lang,
  maxPercent,
  rank,
}: {
  lang: CodingStat;
  maxPercent: number;
  rank: number;
}) {
  const barWidth = (lang.percent / maxPercent) * 100;
  return (
    <div className="cs-row">
      <span className="cs-rank">#{rank}</span>
      <div className="cs-lang">
        <span className="cs-lang-name">{lang.name}</span>
        <div className="cs-bar">
          <div className="cs-fill" style={{ width: `${barWidth}%` }} />
        </div>
      </div>
      <span className="cs-time">{formatHours(lang.total_seconds)}</span>
      <span className="cs-percent">{lang.percent.toFixed(1)}%</span>
    </div>
  );
}

export default function CodingStats() {
  const [data, setData] = useState<CodingData | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    function render(d: CodingData) {
      setData(d);
    }
    function renderError() {
      setError(true);
    }

    if (!WAKAPI_ENDPOINT || !WAKAPI_USERNAME) {
      render(fallbackCodingStats);
      return;
    }
    if (typeof fetch !== "function") {
      render(fallbackCodingStats);
      return;
    }

    const ctrl =
      typeof AbortController === "function" ? new AbortController() : null;
    const timer = setTimeout(() => ctrl?.abort(), TIMEOUT_MS);

    const url =
      WAKAPI_ENDPOINT.indexOf("?") === -1
        ? `${WAKAPI_ENDPOINT}?username=${WAKAPI_USERNAME}`
        : `${WAKAPI_ENDPOINT}&username=${WAKAPI_USERNAME}`;

    fetch(url, {
      headers: { Accept: "application/json" },
      signal: ctrl ? ctrl.signal : undefined,
    })
      .then((res) => {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .then((d: { data: CodingData }) => {
        clearTimeout(timer);
        //console.log("Coding stats fetched:", d);
        const data = d?.data;
        if (!data || !Array.isArray(data.languages)) {
          renderError();
          return;
        }
        render({
          languages: data.languages,
          total_seconds: data.total_seconds,
          days_tracked: data.days_including_holidays,
          daily_average: data.daily_average,
        } as CodingData);
      })
      .catch(() => {
        clearTimeout(timer);
        renderError();
      });

    return () => {
      clearTimeout(timer);
      ctrl?.abort();
    };
  }, []);

  const maxPercent = data?.languages.length ? data.languages[0].percent : 100;

  return (
    <section
      id="codingstat"
      className="px-6 md:px-10 py-24 md:py-36 border-t hairline"
    >
      <div className="max-w-7xl mx-auto">
        <Reveal className="mb-12 md:mb-16">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-medium tracking-[-0.03em] leading-[1.05] mb-4 max-w-2xl text-balance">
            {coding.heading.pre}
            <span className="text-accent italic font-medium">
              {coding.heading.accent}
            </span>
            {coding.heading.post}
          </h2>
          <p className="text-ink-300 leading-[1.6] max-w-xl">
            {coding.subline}
          </p>
        </Reveal>

        <Reveal delay={1}>
          <div className="bezel">
            <div className="bezel-inner p-5 pb-5 md:p-7 md:pb-7 relative">
              <div
                className="cloud cloud-1 -top-24 -right-16 w-[420px] h-[420px]"
                aria-hidden="true"
              ></div>
              <div className="cs-header">
                <p className="text-[10px] uppercase tracking-[0.18em] text-ink-400 font-mono mb-0 truncate">
                  {coding.breakdown}
                </p>
                <p className="cs-total">
                  <span className="cs-total-value">
                    {data ? formatHours(data.total_seconds) : "—"}
                  </span>{" "}
                  tracked · <span>{data ? data.days_tracked : "—"}</span> days
                </p>
              </div>
              <p className="cs-total cs-daily">
                avg{" "}
                <span className="cs-total-value">
                  {data ? formatHours(data.daily_average) : "—"}
                </span>{" "}
                <span className="cs-daily-label">/ day</span>
              </p>
              
              {data ? (
                data.languages
                  .slice(0, 6)
                  .map((lang, i) => (
                    <CodingRow
                      key={lang.name}
                      lang={lang}
                      maxPercent={maxPercent}
                      rank={i + 1}
                    />
                  ))
              ) : (
                <>
                  {[70, 50, 35, 25, 18, 12].map((w) => (
                    <div className="cs-row" key={w}>
                      <span className="cs-rank cs-skel">&nbsp;</span>
                      <div className="cs-lang">
                        <span className="cs-lang-name cs-skel">
                          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span>
                        <div className="cs-bar">
                          <div
                            className="cs-fill cs-skel"
                            style={{ width: `${w}%` }}
                          />
                        </div>
                      </div>
                      <span className="cs-time cs-skel">
                        &nbsp;&nbsp;&nbsp;
                      </span>
                      <span className="cs-percent cs-skel">
                        &nbsp;&nbsp;&nbsp;
                      </span>
                    </div>
                  ))}
                </>
              )}

              {error && (
                <p className="mt-4 text-xs font-mono text-ink-400">
                  {coding.error}
                </p>
              )}
            </div>
          </div>
        </Reveal>
      </div>
    </section>
  );
}
